// Code generated by scripts/generate-plugin-contract.js; DO NOT EDIT.
package plugincontract

import "encoding/json"

const ProtocolVersion uint32 = 2
const MinProtocolVersion uint32 = 2
const MaxProtocolVersion uint32 = 2
const MaxMetadataBytes = 65536
const MaxPayloadBytes = 4194304
const MaxBufferedBytes = 8454144
const MaxInflightCalls = 64
const MaxParkedCalls = 1024
const MaxInvokeTimeoutMs = 10000
const MaxHandshakeTimeoutMs = 2000
const MaxDrainTimeoutMs = 10000
const MaxPackageBytes = 134217728
const MaxPackageMetadataBytes = 1048576
const MaxPackageFiles = 1024

const (
	KindHello       = "hello"
	KindHelloResult = "hello.result"
	KindCall        = "call"
	KindResult      = "result"
	KindError       = "error"
	KindCancel      = "cancel"
)

const (
	CodeRpcInvalid              = "plugin_rpc_invalid"
	CodeRpcIncompatible         = "plugin_rpc_incompatible"
	CodeRpcUnauthorized         = "plugin_rpc_unauthorized"
	CodeRpcMetadataLimit        = "plugin_rpc_metadata_limit"
	CodeRpcPayloadLimit         = "plugin_rpc_payload_limit"
	CodeRpcBufferLimit          = "plugin_rpc_buffer_limit"
	CodeRpcInflightLimit        = "plugin_rpc_inflight_limit"
	CodeRpcTimeout              = "plugin_rpc_timeout"
	CodeRpcCancelled            = "plugin_rpc_cancelled"
	CodeRpcClosed               = "plugin_rpc_closed"
	CodeRpcMethodUnknown        = "plugin_rpc_method_unknown"
	CodeRpcParentUnknown        = "plugin_rpc_parent_unknown"
	CodeNextCalledTwice         = "plugin_next_called_twice"
	CodeContributionUnknown     = "plugin_contribution_unknown"
	CodeContributionUnavailable = "plugin_contribution_unavailable"
	CodeGenerationUnknown       = "plugin_generation_unknown"
)

var GatewayRequestFrozenTopLevel = []string{"session_id", "sessionId", "session", "conversation_id", "thread_id", "previous_response_id", "response_id", "store", "prompt_cache_key"}
var GatewayRequestFrozenMetadata = []string{"session_id", "conversation_id", "thread_id"}

type Fault struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type ProtocolRange struct {
	Min uint32 `json:"min"`
	Max uint32 `json:"max"`
}

type Message struct {
	Kind            string          `json:"kind"`
	ProtocolVersion uint32          `json:"protocolVersion"`
	ID              string          `json:"id"`
	Method          string          `json:"method,omitempty"`
	Token           string          `json:"token,omitempty"`
	Parent          string          `json:"parent,omitempty"`
	Deadline        int64           `json:"deadline,omitempty"`
	Value           json.RawMessage `json:"value,omitempty"`
	Supported       *ProtocolRange  `json:"supported,omitempty"`
	Error           *Fault          `json:"error,omitempty"`
}
