'use strict';

const path = require('path');
const nodeFs = require('node:fs');
const { spawnSync } = require('node:child_process');
const { BaseMultiplexerDriver } = require('./base-driver');
const { MULTIPLEXER_TYPE } = require('../types');
const { TMUX_SAFE_RENDER_ENV_KEYS } = require('../tmux-session-env');

const DISABLE_ENV = 'AIH_NO_PERSIST';
const RUN_EXIT_MARKER = '__AIH_RUN_EXIT:';
const RUN_SESSION_NAME = 'run';
const PSMUX_WINGET_PACKAGE_ID = 'marlocarlo.psmux';

const WINDOWS_TMUX_CANDIDATES = [
  { command: 'psmux', viaShell: false },
  { command: 'tmux', viaShell: false },
  { command: 'C:\\msys64\\usr\\bin\\tmux.exe', viaShell: false },
  { command: 'C:\\cygwin64\\bin\\tmux.exe', viaShell: false }
];

const TRANSPARENT_CONF = [
  '# Auto-generated by ai-home. Keeps tmux invisible under the aih runtime.',
  'set -g status off',
  'set -g window-size latest',
  'set -g aggressive-resize off',
  'set -g escape-time 0',
  'set -gq allow-passthrough on',
  // Version tolerance: extended-keys needs tmux >= 3.2, extended-keys-format
  // needs tmux >= 3.5. `-q` makes older tmux silently skip unknown options
  // (no error banner, behaviour unchanged) instead of forcing an upgrade.
  'set -gq extended-keys on',
  'set -gq extended-keys-format csi-u',
  'set -g terminal-features[0] "xterm*:clipboard:ccolour:cstyle:focus:title:extkeys:sync"',
  'set -gqu terminal-features[3]',
  'set -gqu terminal-features[4]',
  'set -gqu terminal-features[5]',
  'set -g mouse on',
  'set -g history-limit 50000',
  'set -g remain-on-exit off',
  'set -g destroy-unattached off',
  'set -g detach-on-destroy on',
  ''
].join('\n');

const PSMUX_TRANSPARENT_CONF = [
  '# Auto-generated by ai-home. Keeps psmux invisible under the aih runtime.',
  'set -g default-shell powershell',
  'set -g status off',
  'set -g window-size latest',
  'set -g aggressive-resize off',
  'set -g escape-time 0',
  'set -gq allow-passthrough on',
  // psmux does not implement the extended-keys option (modified Enter is
  // hardcoded in its input layer: Shift/Alt+Enter -> ESC+CR, Ctrl+Enter ->
  // ConPTY-native LF injection, so the keys work regardless). It parses and
  // stores unknown options inertly, so setting these here only makes the
  // provider CLIs' `show -gqv extended-keys` probe return "on" and silences
  // their "extended-keys is off" warning. `-q` keeps any older build that
  // rejected unknown options silent instead of erroring at server start.
  'set -gq extended-keys on',
  'set -gq extended-keys-format csi-u',
  'set -g terminal-features[0] "xterm*:clipboard:ccolour:cstyle:focus:title:extkeys:sync"',
  'set -gqu terminal-features[3]',
  'set -gqu terminal-features[4]',
  'set -gqu terminal-features[5]',
  'set -g mouse on',
  'set -g history-limit 50000',
  'set -g remain-on-exit off',
  'set -g destroy-unattached off',
  ''
].join('\n');

function quote(value) {
  return `'${String(value == null ? '' : value).replace(/'/g, "'\\''")}'`;
}

function joinWinPath(...parts) {
  return parts
    .map((part) => String(part || '').trim().replace(/[\\/]+$/, ''))
    .filter(Boolean)
    .join('\\');
}

function pushUniqueCandidate(candidates, seen, candidate) {
  const command = String(candidate && candidate.command || '').trim();
  if (!command) return;
  const key = command.toLowerCase();
  if (seen.has(key)) return;
  seen.add(key);
  candidates.push({ ...candidate, command });
}

function resolveTmuxExecution(options = {}) {
  return {
    command: String(options.command || 'tmux').trim() || 'tmux',
    spawnSync: typeof options.spawnSync === 'function' ? options.spawnSync : spawnSync
  };
}

class TmuxDriver extends BaseMultiplexerDriver {
  constructor() {
    super();
    this._cachedDetect = null;
    this._cachedSystemdRunSupported = null;
  }

  get name() {
    return MULTIPLEXER_TYPE.TMUX;
  }

  detect(options = {}) {
    const platform = options.platform || process.platform;
    const env = options.env || process.env;
    const usingInjectedProbes = !!(options.spawnSync || options.resolveCommandPath || options.existsSync);

    if (!usingInjectedProbes && this._cachedDetect) return this._cachedDetect;

    let result;
    if (String(env[DISABLE_ENV] || '') === '1') {
      result = { available: false, reason: 'disabled', command: '', viaShell: false };
    } else if (platform === 'win32') {
      result = this._detectWindowsTmux(options);
    } else {
      result = this._detectPosixTmux(options);
    }

    if (!usingInjectedProbes) this._cachedDetect = result;
    return result;
  }

  _detectPosixTmux(options = {}) {
    const platform = options.platform || process.platform;
    const env = options.env || process.env;
    let command = '';
    if (typeof options.resolveCommandPath === 'function') {
      try {
        command = options.resolveCommandPath('tmux', { platform, env }) || '';
      } catch (_error) {
        command = '';
      }
    }
    if (!command && typeof options.spawnSync === 'function') {
      try {
        const probe = options.spawnSync('tmux', ['-V'], { stdio: 'ignore' });
        if (probe && probe.status === 0) command = 'tmux';
      } catch (_error) {
        command = '';
      }
    }
    return command
      ? { available: true, reason: 'ok', command, viaShell: false }
      : { available: false, reason: 'not-found', command: '', viaShell: false };
  }

  _detectWindowsTmux(options = {}) {
    const env = options.env || process.env;
    const platform = options.platform || process.platform;
    const resolveCommandPath = typeof options.resolveCommandPath === 'function' ? options.resolveCommandPath : null;
    const existsSync = typeof options.existsSync === 'function' ? options.existsSync : null;
    const spawnImpl = typeof options.spawnSync === 'function' ? options.spawnSync : null;

    const candidates = [];
    const seen = new Set();
    if (resolveCommandPath) {
      try {
        const psmuxPath = resolveCommandPath('psmux', { platform, env });
        if (psmuxPath) pushUniqueCandidate(candidates, seen, { command: psmuxPath, viaShell: false });
      } catch (_error) { /* continue */ }
      try {
        const tmuxPath = resolveCommandPath('tmux', { platform, env });
        if (tmuxPath) pushUniqueCandidate(candidates, seen, { command: tmuxPath, viaShell: false });
      } catch (_error) { /* continue */ }
    }

    const localAppData = env.LOCALAPPDATA || (env.USERPROFILE ? joinWinPath(env.USERPROFILE, 'AppData', 'Local') : '');
    if (localAppData) {
      pushUniqueCandidate(candidates, seen, {
        command: joinWinPath(localAppData, 'Microsoft', 'WinGet', 'Links', 'psmux.exe'),
        viaShell: false
      });
    }

    for (const item of WINDOWS_TMUX_CANDIDATES) {
      pushUniqueCandidate(candidates, seen, item);
    }

    for (const candidate of candidates) {
      if (path.isAbsolute(candidate.command)) {
        if (existsSync) {
          try {
            if (existsSync(candidate.command)) return { available: true, reason: 'ok', ...candidate };
          } catch (_error) { /* try next */ }
        }
        continue;
      }
      if (spawnImpl) {
        try {
          const probe = spawnImpl(candidate.command, ['-V'], { stdio: 'ignore', shell: candidate.viaShell });
          if (probe && probe.status === 0) return { available: true, reason: 'ok', ...candidate };
        } catch (_error) { /* try next */ }
      }
    }

    return {
      available: false,
      reason: 'not-found',
      command: '',
      viaShell: false,
      installHint: `Install psmux (recommended): winget install ${PSMUX_WINGET_PACKAGE_ID}`
    };
  }

  isSystemdScopeSupported(options = {}) {
    const platform = options.platform || process.platform;
    const env = options.env || process.env;
    if (platform !== 'linux' || !String(env.XDG_RUNTIME_DIR || '').trim()) return false;
    const usingInjectedProbe = typeof options.spawnSync === 'function';
    if (!usingInjectedProbe && this._cachedSystemdRunSupported !== null) {
      return this._cachedSystemdRunSupported;
    }
    const spawnImpl = resolveTmuxExecution(options).spawnSync;
    try {
      const supported = spawnImpl('systemd-run', ['--version'], { stdio: 'ignore' }).status === 0;
      if (!usingInjectedProbe) this._cachedSystemdRunSupported = supported;
      return supported;
    } catch (_error) {
      if (!usingInjectedProbe) this._cachedSystemdRunSupported = false;
      return false;
    }
  }

  buildLaunchArgs(options = {}) {
    const command = options.command || 'tmux';
    const inner = options.inner || {};
    const socket = options.socket || 'default';
    const session = options.session || 'default';
    const tmuxArgs = ['-L', String(socket)];

    if (options.confPath) tmuxArgs.push('-f', String(options.confPath));
    if (options.attachExisting) {
      tmuxArgs.push('attach-session');
      if (!options.share && options.detachOnAttach !== false) tmuxArgs.push('-d');
      tmuxArgs.push('-t', session);
      return { command, args: tmuxArgs, socket, session };
    }

    if (options.detached) {
      tmuxArgs.push('new-session', '-A', '-d');
      this._appendNewSessionEnvArgs(tmuxArgs, options.env);
      tmuxArgs.push('-s', session);
      if (options.cwd) tmuxArgs.push('-c', String(options.cwd));
      tmuxArgs.push('--', String(inner.command));
      for (const arg of (Array.isArray(inner.args) ? inner.args : [])) tmuxArgs.push(String(arg));
      return { command, args: tmuxArgs, socket, session, detached: true };
    }

    tmuxArgs.push('new-session');
    this._appendNewSessionEnvArgs(tmuxArgs, options.env);
    tmuxArgs.push('-s', session);
    if (options.cwd) tmuxArgs.push('-c', String(options.cwd));
    tmuxArgs.push('--', String(inner.command));
    const innerArgs = Array.isArray(inner.args) ? inner.args : [];
    for (const arg of innerArgs) tmuxArgs.push(String(arg));
    return { command, args: tmuxArgs, socket, session };
  }

  _appendNewSessionEnvArgs(targetArgs, env) {
    if (!env || typeof env !== 'object') return;
    for (const key of TMUX_SAFE_RENDER_ENV_KEYS) {
      if (typeof env[key] !== 'string') continue;
      const value = env[key].trim();
      if (!value) continue;
      targetArgs.push('-e', `${key}=${value}`);
    }
  }

  listSessions(socket, options = {}) {
    const execution = resolveTmuxExecution(options);
    const args = ['-L', String(socket), 'list-sessions'];
    if (options.format) {
      args.push('-F', options.format);
    }
    return execution.spawnSync(execution.command, args, { encoding: 'utf8' });
  }

  spawnHeadlessRun(options = {}) {
    const execution = resolveTmuxExecution(options);
    const socket = String(options.socket || '').trim();
    const shellCommand = String(options.shellCommand || '').trim();
    if (!socket || !shellCommand) {
      return { ok: false, error: 'tmux_run_invalid_options' };
    }
    const tmuxArgv = [
      '-L', socket,
      'new-session', '-d', '-s', RUN_SESSION_NAME,
      ...(options.cwd ? ['-c', String(options.cwd)] : []),
      '--', 'sh', '-c', shellCommand
    ];
    const useScope = options.useSystemdScope !== false && this.isSystemdScopeSupported(options);
    const argv = useScope
      ? ['systemd-run', '--user', '--scope', '--collect', '-q', '--', execution.command, ...tmuxArgv]
      : [execution.command, ...tmuxArgv];
    const result = execution.spawnSync(argv[0], argv.slice(1), {
      env: options.env || process.env,
      stdio: 'ignore'
    });
    if (result.status !== 0) {
      if (useScope) {
        const fallback = execution.spawnSync(execution.command, tmuxArgv, { env: options.env || process.env, stdio: 'ignore' });
        if (fallback.status === 0) return { ok: true, socket, session: RUN_SESSION_NAME, scoped: false };
      }
      return { ok: false, error: `tmux_spawn_failed_status_${result.status}` };
    }
    return { ok: true, socket, session: RUN_SESSION_NAME, scoped: useScope };
  }

  hasRun(socket, options = {}) {
    const execution = resolveTmuxExecution(options);
    try {
      return execution.spawnSync(execution.command, ['-L', String(socket), 'has-session', '-t', RUN_SESSION_NAME], { stdio: 'ignore' }).status === 0;
    } catch (_error) {
      return false;
    }
  }

  killRun(socket, options = {}) {
    const execution = resolveTmuxExecution(options);
    try {
      execution.spawnSync(execution.command, ['-L', String(socket), 'kill-server'], { stdio: 'ignore' });
    } catch (_error) { /* server gone is fine */ }
  }

  runSocketPath(socket, options = {}) {
    const env = options.env || process.env;
    const base = String(env.TMUX_TMPDIR || '').trim() || '/tmp';
    const uid = typeof process.getuid === 'function' ? process.getuid() : 0;
    return path.join(base, `tmux-${uid}`, String(socket));
  }

  cleanupRun(socket, options = {}) {
    if (!String(socket || '').trim()) return;
    this.killRun(socket, options);
    const fs = options.fs || nodeFs;
    try { fs.unlinkSync(this.runSocketPath(socket, options)); } catch (_error) { /* ignored */ }
  }

  sendInput(socket, text, options = {}) {
    const execution = resolveTmuxExecution(options);
    const value = String(text == null ? '' : text);
    if (value) {
      const sent = execution.spawnSync(execution.command, ['-L', String(socket), 'send-keys', '-t', RUN_SESSION_NAME, '-l', '--', value], { stdio: 'ignore' });
      if (sent.status !== 0) return false;
    }
    if (options.appendNewline !== false) {
      return execution.spawnSync(execution.command, ['-L', String(socket), 'send-keys', '-t', RUN_SESSION_NAME, 'Enter'], { stdio: 'ignore' }).status === 0;
    }
    return true;
  }
}

module.exports = {
  TmuxDriver,
  RUN_EXIT_MARKER,
  RUN_SESSION_NAME,
  TRANSPARENT_CONF,
  PSMUX_TRANSPARENT_CONF
};
