'use strict';

// Persistent sessions: run the provider CLI inside tmux so a session started
// locally survives the foreground client and can be re-attached later — start
// `aih claude 1` at your desk, walk away, SSH back into the same host, then
// choose it from `aih claude sessions` or use -M/-R to target the exact session.
//
// tmux IS the engine — we never reinvent a multiplexer. tmux's panes, copy-mode,
// scrollback, mouse and resilience are the whole point. We just wrap the launch.
//
// Addressing model — the part that fixes single-account lock-in:
//   * socket  = per ACCOUNT  (`tmux -L aih-<provider>-<accountRef>`). One tmux server per
//     account, created with that account's fully isolated env, so credentials
//     never cross account boundaries. Secrets ride the process env ONLY — never
//     tmux `-e`/argv, which would leak to `ps`.
//   * session = a fresh per-launch project session or an explicit LABEL. A
//     single account server therefore holds MANY independent sessions. Bare
//     launches never select an existing process; sessions / -M / -R are the
//     explicit paths for entering, mirroring, or taking over one.
//
// Cross-platform: tmux is the engine on macOS / Linux / WSL, and on native
// Windows via a tmux-compatible binary — `psmux` (native ConPTY, speaks tmux's
// CLI) or an MSYS2/Cygwin `tmux.exe`. detectTmux() finds whichever is present.

const fs = require('fs');
const path = require('path');
const { resolveCommandPath: defaultResolveCommandPath } = require('./command-path');
const { GATEWAY_RUNTIME_SCOPE } = require('../account/runtime-target');

const MARKER_ENV = 'AIH_PERSIST_ACTIVE';
const DISABLE_ENV = 'AIH_NO_PERSIST';
const SESSION_ENV = 'AIH_SESSION';
const RESUME_ENV = 'AIH_SESSION_RESUME';
const MIRROR_ENV = 'AIH_SESSION_MIRROR';
const TARGET_ENV = 'AIH_SESSION_TARGET';
// Set by the restore engine on its `aih <provider> <id>` children: create the
// planned session detached (`new-session -Ad`) and exit instead of attaching.
// This lets a reboot-restore reuse the ENTIRE normal launch pipeline (account
// env isolation, config sync, runtime markers) without a foreground terminal.
const DETACHED_ENV = 'AIH_PERSIST_DETACHED';
const SOCKET_PREFIX = 'aih';
const PSMUX_INSTALL_URL = 'https://github.com/psmux/psmux';
const PSMUX_WINGET_PACKAGE_ID = 'marlocarlo.psmux';
const SESSION_LIST_SEPARATOR = '\x1f';
const PSMUX_CODEX_LAUNCH_RUNTIME_MARKER_KEY = 'AIH_PSMUX_CODEX_LAUNCH_RUNTIME';
const PSMUX_CODEX_LAUNCH_RUNTIME_MARKER_VALUE = '2026-07-native-psmux-codex-default';
const PROVIDER_SUPERVISOR_RUNTIME_MARKER_KEY = 'AIH_PERSIST_PROVIDER_SUPERVISOR_RUNTIME';
const PROVIDER_SUPERVISOR_RUNTIME_MARKER_VALUE = '2026-07-provider-supervisor-v1';
const TMUX_UTF8_ENV_KEYS = Object.freeze(['LANG', 'LC_CTYPE', 'LC_ALL']);
const TMUX_SAFE_RENDER_ENV_KEYS = Object.freeze([
  'CLAUDE_CODE_ALT_SCREEN_FULL_REPAINT',
  'CLAUDE_CODE_FORCE_SYNC_OUTPUT',
  'CLAUDE_CODE_DISABLE_VIRTUAL_SCROLL',
  'NODE_PATH',
  'AIH_CLAUDE_TMUX_RENDER_RUNTIME',
  'AIH_PROVIDER_SESSION_CORRELATION_ID',
  PSMUX_CODEX_LAUNCH_RUNTIME_MARKER_KEY,
  PROVIDER_SUPERVISOR_RUNTIME_MARKER_KEY
]);
const UTF8_RUNTIME_MARKER_KEY = 'AIH_PERSIST_UTF8_RUNTIME';
const UTF8_RUNTIME_MARKER_VALUE = '2026-06-utf8';
const CLAUDE_RENDER_RUNTIME_MARKER_KEY = 'AIH_CLAUDE_TMUX_RENDER_RUNTIME';
const CLAUDE_RENDER_RUNTIME_MARKER_VALUE = '2026-06-render-v2';

const TRANSPARENT_CONF = [
  '# Auto-generated by ai-home. Keeps tmux invisible under the aih runtime.',
  'set -g status off',
  'set -g window-size latest',
  // Keep aggressive-resize OFF (explicitly, not by omission, so re-sourcing this
  // file into an already-running server actively resets a previously-on value).
  // One aih account socket hosts MANY sessions (per project) and mirror mode
  // (-M) attaches MULTIPLE clients to one session. tmux's manual warns
  // aggressive-resize is "poor for interactive programs such as shells" and that
  // "the window may resize when the current window is changed on another
  // session". Under our multi-session / multi-client server that means another
  // session's activity silently resizes the live window out from under an
  // interactive TUI, which redraws incrementally and leaves stale cells (the
  // stray glyphs in column 1 that a manual terminal resize — a full SIGWINCH
  // redraw — wipes clean). Off keeps each window pinned to its attached client.
  'set -g aggressive-resize off',
  'set -g escape-time 0',
  'set -gq allow-passthrough on',
  // Inner panes (Codex-style TUIs) may request extended keys themselves; using
  // "on" forwards those requests to the outer terminal only when a pane asks for
  // it, instead of "always" which unconditionally puts the outer SSH terminal into
  // CSI-u mode. "always" causes Chinese/CJK input bytes to be re-encoded as
  // CSI-u escape sequences by the SSH client, which breaks multibyte input in
  // terminals that support the Kitty keyboard protocol.
  'set -g extended-keys on',
  'set -g extended-keys-format csi-u',
  // Claude Code's fullscreen renderer updates large alternate-screen regions
  // during scroll. Let tmux batch those frames when the outer xterm-compatible
  // terminal supports synchronized updates, otherwise stale edge cells can
  // become visible during rapid redraw.
  'set -g terminal-features[0] "xterm*:clipboard:ccolour:cstyle:focus:title:extkeys:sync"',
  'set -gqu terminal-features[3]',
  'set -gqu terminal-features[4]',
  'set -gqu terminal-features[5]',
  'set -g mouse on',
  'set -g history-limit 50000',
  'set -g remain-on-exit off',
  'set -g destroy-unattached off',
  'set -g detach-on-destroy on',
  ''
].join('\n');

const PSMUX_TRANSPARENT_CONF = [
  '# Auto-generated by ai-home. Keeps psmux invisible under the aih runtime.',
  // psmux defaults to PowerShell 7 (`pwsh`). Many native Windows hosts only
  // have Windows PowerShell 5.1; psmux documents `powershell` as the portable
  // setting for the OS-provided shell.
  'set -g default-shell powershell',
  'set -g status off',
  'set -g window-size latest',
  'set -g aggressive-resize off',
  'set -g escape-time 0',
  'set -gq allow-passthrough on',
  'set -g terminal-features[0] "xterm*:clipboard:ccolour:cstyle:focus:title:extkeys:sync"',
  'set -gqu terminal-features[3]',
  'set -gqu terminal-features[4]',
  'set -gqu terminal-features[5]',
  'set -g mouse on',
  'set -g history-limit 50000',
  'set -g remain-on-exit off',
  'set -g destroy-unattached off',
  ''
].join('\n');

// Common install locations for a tmux-compatible binary on native Windows.
// Ordered by preference: native ConPTY (psmux) first, then POSIX-layer tmux.
const WINDOWS_TMUX_CANDIDATES = [
  { command: 'psmux', viaShell: false },
  { command: 'tmux', viaShell: false },
  { command: 'C:\\msys64\\usr\\bin\\tmux.exe', viaShell: false },
  { command: 'C:\\cygwin64\\bin\\tmux.exe', viaShell: false }
];

let detectCache = null;

function sanitizeKeyPart(value) {
  const cleaned = String(value == null ? '' : value)
    .trim()
    .replace(/[^A-Za-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
  return cleaned || 'default';
}

function normalizeRuntimeScope(value) {
  const runtimeScope = String(value || '').trim();
  if (runtimeScope === GATEWAY_RUNTIME_SCOPE) return runtimeScope;
  return /^acct_[a-f0-9]{20}$/.test(runtimeScope) ? runtimeScope : '';
}

// Short, stable, filename-safe hash of a string (for disambiguating project
// paths whose basenames collide). Not cryptographic — only needs to be stable.
function shortHash(value) {
  let h = 5381;
  const text = String(value == null ? '' : value);
  for (let i = 0; i < text.length; i += 1) {
    h = ((h << 5) + h + text.charCodeAt(i)) >>> 0;
  }
  return h.toString(36).slice(0, 6).padStart(6, '0');
}

// Per-runtime-target socket: account targets use their accountRef; the gateway
// target uses the explicit "gateway" scope and never impersonates an account.
function deriveSocket(cliName, runtimeScope) {
  const normalizedScope = normalizeRuntimeScope(runtimeScope);
  if (!normalizedScope) throw new Error('invalid_persistent_runtime_scope');
  return `${SOCKET_PREFIX}-${sanitizeKeyPart(cliName)}-${normalizedScope}`;
}

// Stable per-project grouping name, or the exact identity of an explicitly
// labelled session. Bare launches append a unique suffix before creating tmux.
function deriveSessionName(options = {}) {
  const label = String(options.label || '').trim();
  if (label) return `s-${sanitizeKeyPart(label)}`;
  const cwd = String(options.cwd || '').trim();
  if (!cwd) return 'default';
  const base = sanitizeKeyPart(path.basename(cwd) || 'root');
  return `p-${base}-${shortHash(cwd)}`;
}

// Bare launches always receive a collision-resistant name. The stable project
// name remains only a grouping prefix; it is never implicit authorization to
// attach to an existing tmux process.
function deriveFreshSessionName(options = {}) {
  const base = deriveSessionName({ cwd: options.cwd });
  const now = Math.max(0, Math.floor(Number(options.now)));
  const pid = Math.max(0, Math.floor(Number(options.pid)));
  const parts = [
    Number.isFinite(now) ? now.toString(36) : Date.now().toString(36)
  ];
  if (Number.isFinite(pid) && pid > 0) parts.push(pid.toString(36));
  return `${base}-${parts.join('-')}`;
}

function isSafeSessionName(value) {
  return /^[A-Za-z0-9._-]+$/.test(String(value || '').trim());
}

function compactSessionText(value) {
  return String(value == null ? '' : value)
    .replace(/\x1b\][^\x07]*(?:\x07|\x1b\\)/g, '')
    .replace(/\x1b\[[0-?]*[ -/]*[@-~]/g, '')
    .replace(/[\r\n\t]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 120);
}

function shouldUseDescription(value) {
  const text = compactSessionText(value);
  if (!text) return false;
  if (/^\[(?:o|a):[^\]]+\]$/.test(text)) return false;
  if (/^[\u2800-\u28ff]\s+\S+/.test(text)) return false;
  if (/^(tmux|psmux|sh|bash|zsh|fish|node|codex|claude|gemini|agy|opencode)$/i.test(text)) return false;
  return true;
}

function deriveSessionDescription(session = {}) {
  const agentTitle = compactSessionText(session.agentTitle);
  if (shouldUseDescription(agentTitle)) return agentTitle;
  const title = compactSessionText(session.title);
  if (shouldUseDescription(title)) return title;
  const windowName = compactSessionText(session.windowName);
  if (shouldUseDescription(windowName)) return windowName;
  const command = compactSessionText(session.command);
  if (shouldUseDescription(command)) return command;
  const sessionPath = compactSessionText(session.path);
  return sessionPath ? path.basename(sessionPath) : '';
}

function shellQuote(value) {
  return `"${String(value || '').replace(/(["\\$`])/g, '\\$1')}"`;
}

// Resolve the tmux-compatible engine for this host. Memoised because spawnPty
// may be called repeatedly (auth-refresh restarts). On Windows we probe a list
// of known psmux/MSYS2/Cygwin locations; elsewhere we resolve `tmux` on PATH.
function detectTmux(options = {}) {
  const platform = options.platform || process.platform;
  const env = options.env || process.env;
  const usingInjectedProbes = !!(options.spawnSync || options.resolveCommandPath || options.existsSync);

  if (!usingInjectedProbes && detectCache) return detectCache;

  let result;
  if (String(env[DISABLE_ENV] || '') === '1') {
    result = { available: false, reason: 'disabled', command: '', viaShell: false };
  } else if (platform === 'win32') {
    result = detectWindowsTmux(options);
  } else {
    result = detectPosixTmux(options);
  }

  if (!usingInjectedProbes) detectCache = result;
  return result;
}

function detectPosixTmux(options = {}) {
  const platform = options.platform || process.platform;
  const env = options.env || process.env;
  let command = '';
  if (typeof options.resolveCommandPath === 'function') {
    try {
      command = options.resolveCommandPath('tmux', { platform, env }) || '';
    } catch (_error) {
      command = '';
    }
  }
  if (!command && typeof options.spawnSync === 'function') {
    try {
      const probe = options.spawnSync('tmux', ['-V'], { stdio: 'ignore' });
      if (probe && probe.status === 0) command = 'tmux';
    } catch (_error) {
      command = '';
    }
  }
  return command
    ? { available: true, reason: 'ok', command, viaShell: false }
    : { available: false, reason: 'not-found', command: '', viaShell: false };
}

function pushUniqueCandidate(candidates, seen, candidate) {
  const command = String(candidate && candidate.command || '').trim();
  if (!command) return;
  const key = command.toLowerCase();
  if (seen.has(key)) return;
  seen.add(key);
  candidates.push({ ...candidate, command });
}

function joinWinPath(...parts) {
  return parts
    .map((part) => String(part || '').replace(/^[\\/]+|[\\/]+$/g, ''))
    .filter(Boolean)
    .join('\\');
}

function collectWindowsTmuxCandidates(env = {}) {
  const candidates = [];
  const seen = new Set();
  const localAppData = String(env.LOCALAPPDATA || env.LocalAppData || env.localappdata || '').trim();
  const userProfile = String(env.USERPROFILE || env.UserProfile || env.userprofile || '').trim();
  const wingetLinksDirs = [];
  if (localAppData) wingetLinksDirs.push(joinWinPath(localAppData, 'Microsoft', 'WinGet', 'Links'));
  if (userProfile) wingetLinksDirs.push(joinWinPath(userProfile, 'AppData', 'Local', 'Microsoft', 'WinGet', 'Links'));

  pushUniqueCandidate(candidates, seen, { command: 'psmux', viaShell: false });
  for (const dir of wingetLinksDirs) {
    pushUniqueCandidate(candidates, seen, { command: joinWinPath(dir, 'psmux.exe'), viaShell: false });
  }

  pushUniqueCandidate(candidates, seen, { command: 'tmux', viaShell: false });
  for (const dir of wingetLinksDirs) {
    pushUniqueCandidate(candidates, seen, { command: joinWinPath(dir, 'tmux.exe'), viaShell: false });
  }

  for (const candidate of WINDOWS_TMUX_CANDIDATES.slice(2)) {
    pushUniqueCandidate(candidates, seen, candidate);
  }
  return candidates;
}

function detectWindowsTmux(options = {}) {
  const platform = 'win32';
  const env = options.env || process.env;
  const existsSync = typeof options.existsSync === 'function'
    ? options.existsSync
    : fs.existsSync;
  const resolveCommandPath = typeof options.resolveCommandPath === 'function'
    ? options.resolveCommandPath
    : (cmd, resolveOptions) => defaultResolveCommandPath(cmd, {
      ...resolveOptions,
      spawnSyncImpl: options.spawnSync
    });

  for (const candidate of collectWindowsTmuxCandidates(env)) {
    const cmd = candidate.command;
    const looksLikePath = /[\\/]/.test(cmd);
    if (looksLikePath) {
      let found = false;
      try { found = !!existsSync(cmd); } catch (_error) { found = false; }
      if (found) return { available: true, reason: 'ok', command: cmd, viaShell: candidate.viaShell };
      continue;
    }
    let resolved = '';
    try { resolved = String(resolveCommandPath(cmd, { platform, env }) || '').trim(); } catch (_error) { resolved = ''; }
    if (resolved) return { available: true, reason: 'ok', command: resolved, viaShell: candidate.viaShell };
  }
  return {
    available: false,
    reason: 'windows-no-tmux',
    command: '',
    viaShell: false,
    remediation: 'Install psmux (https://github.com/psmux/psmux) or an MSYS2/Cygwin tmux to enable persistent sessions on Windows.'
  };
}

function buildWindowsPsmuxInstallCommand() {
  return {
    command: 'winget',
    args: [
      'install',
      '--id', PSMUX_WINGET_PACKAGE_ID,
      '--exact',
      '--accept-package-agreements',
      '--accept-source-agreements'
    ],
    display: `winget install --id ${PSMUX_WINGET_PACKAGE_ID} --exact`
  };
}

function installWindowsPsmux(options = {}) {
  const spawnSyncImpl = options.spawnSync;
  if (typeof spawnSyncImpl !== 'function') {
    return { ok: false, reason: 'spawnSync-unavailable', status: null, error: null };
  }
  const install = buildWindowsPsmuxInstallCommand();
  let result;
  try {
    result = spawnSyncImpl(install.command, install.args, { stdio: options.stdio || 'inherit' });
  } catch (error) {
    return { ok: false, reason: 'spawn-failed', status: null, error };
  }
  const status = result && Number.isInteger(result.status) ? result.status : null;
  if (result && result.error) {
    return { ok: false, reason: 'spawn-error', status, error: result.error };
  }
  if (status !== 0) {
    return { ok: false, reason: 'install-failed', status, error: null };
  }
  return { ok: true, reason: 'ok', status, error: null };
}

// Should this particular launch be wrapped? Persistence is for the interactive
// foreground CLI only — never short-lived login/oauth flows, non-TTY runs, or a
// process already inside an aih-managed tmux (avoid nesting).
function shouldPersist(ctx = {}) {
  if (!ctx.tmux || !ctx.tmux.available) return false;
  if (ctx.isLogin) return false;
  if (ctx.isTTY === false) return false;
  const env = ctx.env || {};
  if (String(env[MARKER_ENV] || '') === '1') return false;
  if (String(env[DISABLE_ENV] || '') === '1') return false;
  return true;
}

function getTmuxConfContent(options = {}) {
  return isNativeWindowsPsmuxCommand(options.tmuxCommand || options.tmuxPath, options.platform)
    ? PSMUX_TRANSPARENT_CONF
    : TRANSPARENT_CONF;
}

function ensureTmuxConf(confPath, fsImpl, options = {}) {
  if (!confPath || !fsImpl) return '';
  try {
    fsImpl.mkdirSync(path.dirname(confPath), { recursive: true });
    let current = '';
    try { current = fsImpl.readFileSync(confPath, 'utf8'); } catch (_error) { current = ''; }
    const content = getTmuxConfContent(options);
    if (current !== content) fsImpl.writeFileSync(confPath, content, 'utf8');
    return confPath;
  } catch (_error) {
    return '';
  }
}

function buildTmuxBaseArgs(socket) {
  // Force UTF-8 for every aih tmux client. Remote SSH clients may have LANG=C,
  // and tmux otherwise treats that client as non-UTF-8, corrupting Chinese text
  // on reattach even though the underlying session content is fine.
  return ['-u', '-L', socket];
}

function isNativeWindowsPsmuxCommand(command, platform = process.platform) {
  if (platform !== 'win32') return false;
  const baseName = path.win32.basename(String(command || '').trim()).toLowerCase();
  return baseName === 'psmux' || baseName === 'psmux.exe';
}

function collectTmuxEnvironment(env = {}) {
  return [
    ...TMUX_UTF8_ENV_KEYS,
    ...TMUX_SAFE_RENDER_ENV_KEYS
  ]
    .map((key) => {
      const value = String(env && env[key] || '').trim();
      return { key, value };
    })
    .filter((item) => item.value && !/[\0\r\n]/.test(item.value));
}

function appendTmuxNewSessionEnvArgs(tmuxArgs, env = {}) {
  for (const item of collectTmuxEnvironment(env)) {
    tmuxArgs.push('-e', `${item.key}=${item.value}`);
  }
  tmuxArgs.push('-e', `${UTF8_RUNTIME_MARKER_KEY}=${UTF8_RUNTIME_MARKER_VALUE}`);
}

function buildSetEnvironmentCommands(options = {}) {
  const command = options.tmuxCommand || options.tmuxPath || 'tmux';
  const socket = deriveSocket(options.cliName, options.runtimeScope);
  const targetSession = String(options.sessionName || '').trim();
  const targetArgs = targetSession && isSafeSessionName(targetSession)
    ? ['-t', targetSession]
    : ['-g'];
  return collectTmuxEnvironment(options.env)
    .map((item) => ({
      command,
      args: [
        ...buildTmuxBaseArgs(socket),
        'set-environment',
        ...targetArgs,
        item.key,
        item.value
      ],
      socket,
      key: item.key,
      value: item.value,
      session: targetArgs[0] === '-t' ? targetSession : ''
    }));
}

// Build one explicit tmux operation. User launches use strict create or exact
// attach; only reboot restoration keeps attach-or-create semantics.
function buildTmuxLaunch(inner, options = {}) {
  const command = options.tmuxCommand || options.tmuxPath || 'tmux';
  const socket = deriveSocket(options.cliName, options.runtimeScope);
  const session = options.sessionName
    || deriveSessionName({ cwd: options.cwd, label: options.label });
  const tmuxArgs = buildTmuxBaseArgs(socket);
  if (options.confPath) tmuxArgs.push('-f', String(options.confPath));
  if (options.attachExisting) {
    tmuxArgs.push('attach-session');
    if (!options.share && options.detachOnAttach !== false) tmuxArgs.push('-d');
    tmuxArgs.push('-t', session);
    return { command, args: tmuxArgs, socket, session };
  }
  // Detached restore: `new-session -Ad` is the standard "ensure session
  // exists" idiom — creates the session in the background when missing and is
  // a no-op when it already lives. No client attaches; the tmux command exits
  // immediately. Used by the post-reboot restore engine.
  if (options.detached) {
    tmuxArgs.push('new-session', '-A', '-d');
    appendTmuxNewSessionEnvArgs(tmuxArgs, options.env);
    tmuxArgs.push('-s', session);
    if (options.cwd) tmuxArgs.push('-c', String(options.cwd));
    tmuxArgs.push('--', String(inner.command));
    for (const arg of (Array.isArray(inner.args) ? inner.args : [])) tmuxArgs.push(String(arg));
    return { command, args: tmuxArgs, socket, session, detached: true };
  }
  // Strict create: a collision must fail instead of silently attaching to (or
  // detaching a client from) an existing provider process.
  tmuxArgs.push('new-session');
  appendTmuxNewSessionEnvArgs(tmuxArgs, options.env);
  tmuxArgs.push('-s', session);
  if (options.cwd) tmuxArgs.push('-c', String(options.cwd));
  tmuxArgs.push('--', String(inner.command));
  const innerArgs = Array.isArray(inner.args) ? inner.args : [];
  for (const arg of innerArgs) tmuxArgs.push(String(arg));
  return { command, args: tmuxArgs, socket, session };
}

// Parse `list-sessions -F '#{session_name}\t#{session_attached}...'` output into
// [{ name, attached }] where `attached` is whether a live client is on it now.
function splitSessionListLine(line) {
  if (String(line || '').includes(SESSION_LIST_SEPARATOR)) {
    return String(line || '').split(SESSION_LIST_SEPARATOR);
  }
  return String(line || '').split('\t');
}

function isUtf8RuntimeReadySession(session) {
  return String(session && session.utf8Runtime || '').trim() === UTF8_RUNTIME_MARKER_VALUE;
}

function isClaudeRenderRuntimeReadySession(session) {
  return String(session && session.claudeRenderRuntime || '').trim() === CLAUDE_RENDER_RUNTIME_MARKER_VALUE;
}

function isPsmuxCodexLaunchRuntimeReadySession(session) {
  return String(session && session.psmuxCodexLaunchRuntime || '').trim() === PSMUX_CODEX_LAUNCH_RUNTIME_MARKER_VALUE;
}

function isProviderSupervisorRuntimeReadySession(session) {
  return String(session && session.providerSupervisorRuntime || '').trim() === PROVIDER_SUPERVISOR_RUNTIME_MARKER_VALUE;
}

function isCompletedSessionScreen(value) {
  const text = String(value == null ? '' : value)
    .replace(/\x1b\][^\x07]*(?:\x07|\x1b\\)/g, '')
    .replace(/\x1b\[[0-?]*[ -/]*[@-~]/g, '')
    .replace(/\r/g, '\n')
    .replace(/[ \t]+/g, ' ')
    .toLowerCase()
    .slice(-8000);
  return /\bsession\s+completed\b/.test(text);
}

function getSessionIncompatibility(session, options = {}) {
  if (!session) return '';
  if (session.paneDeadChecked && session.paneDead) return 'pane-dead';
  if (session.screenCompletedChecked && session.screenCompleted) return 'screen-completed';
  if (
    options.requireUtf8Runtime
    && session.utf8RuntimeChecked
    && !isUtf8RuntimeReadySession(session)
  ) return 'utf8-runtime';
  if (
    options.requireClaudeRenderRuntime
    && session.claudeRenderRuntimeChecked
    && !isClaudeRenderRuntimeReadySession(session)
  ) return 'claude-render-runtime';
  if (
    options.requirePsmuxCodexLaunchRuntime
    && session.psmuxCodexLaunchRuntimeChecked
    && !isPsmuxCodexLaunchRuntimeReadySession(session)
  ) return 'psmux-codex-launch-runtime';
  if (
    options.requireProviderSupervisorRuntime
    && session.providerSupervisorRuntimeChecked
    && !isProviderSupervisorRuntimeReadySession(session)
  ) return 'provider-supervisor-runtime';
  return '';
}

function isSessionCompatible(session, options = {}) {
  return !getSessionIncompatibility(session, options);
}

function buildSessionCompatibilityOptions(options = {}) {
  const cliName = String(options.cliName || '').trim().toLowerCase();
  const isLogin = options.isLogin === true;
  return {
    requireUtf8Runtime: options.requireUtf8Runtime !== false,
    requireClaudeRenderRuntime: cliName === 'claude' && !isLogin,
    requirePsmuxCodexLaunchRuntime: cliName === 'codex'
      && !isLogin
      && options.nativeWindowsPsmux === true,
    requireProviderSupervisorRuntime: !isLogin
      && options.gateway !== true
      && options.usesAuthProjection === true
  };
}

function parseSessionList(stdout) {
  return String(stdout || '')
    .split('\n')
    .map((line) => line.replace(/\r$/, ''))
    .filter((line) => line.trim())
    .map((line) => {
      const [
        name,
        attached,
        created,
        sessionPath,
        title,
        windowName,
        command,
        panePid,
        utf8Runtime,
        claudeRenderRuntime,
        paneDead,
        psmuxCodexLaunchRuntime,
        paneCurrentPath,
        providerSupervisorRuntime
      ] = splitSessionListLine(line);
      return {
        name: String(name || '').trim(),
        attached: String(attached || '0').trim() !== '0',
        created: Number(created) || 0,
        // Display path follows the pane's CURRENT cwd; startPath keeps the
        // session's launch directory — the session registry must record the
        // latter so a post-reboot restore recreates the session (and resumes
        // the provider conversation) in the project root, not wherever the
        // user last cd'd to.
        path: String(paneCurrentPath || sessionPath || '').trim(),
        startPath: String(sessionPath || '').trim(),
        title: compactSessionText(title),
        windowName: compactSessionText(windowName),
        command: compactSessionText(command),
        panePid: Number(panePid) || 0,
        utf8Runtime: compactSessionText(utf8Runtime),
        utf8RuntimeChecked: typeof utf8Runtime !== 'undefined',
        utf8RuntimeReady: String(utf8Runtime || '').trim() === UTF8_RUNTIME_MARKER_VALUE,
        claudeRenderRuntime: compactSessionText(claudeRenderRuntime),
        claudeRenderRuntimeChecked: typeof claudeRenderRuntime !== 'undefined',
        claudeRenderRuntimeReady: String(claudeRenderRuntime || '').trim() === CLAUDE_RENDER_RUNTIME_MARKER_VALUE,
        paneDead: String(paneDead || '').trim() === '1',
        paneDeadChecked: typeof paneDead !== 'undefined',
        psmuxCodexLaunchRuntime: compactSessionText(psmuxCodexLaunchRuntime),
        psmuxCodexLaunchRuntimeChecked: typeof psmuxCodexLaunchRuntime !== 'undefined',
        psmuxCodexLaunchRuntimeReady: String(psmuxCodexLaunchRuntime || '').trim() === PSMUX_CODEX_LAUNCH_RUNTIME_MARKER_VALUE,
        providerSupervisorRuntime: compactSessionText(providerSupervisorRuntime),
        providerSupervisorRuntimeChecked: typeof providerSupervisorRuntime !== 'undefined',
        providerSupervisorRuntimeReady: String(providerSupervisorRuntime || '').trim() === PROVIDER_SUPERVISOR_RUNTIME_MARKER_VALUE
      };
    })
    .filter((s) => s.name);
}

// Decide how one requested session should be handled. The caller must declare
// its intent explicitly:
//   create — strict fresh create; never reuse existing state
//   select — enter this exact existing target; never create or substitute
//   upsert — named create-or-enter behavior
// Returns { session, action }:
//   'new'          — create the requested session
//   'reattach'     — the session exists but its previous client is gone (the
//                    reconnect case: closed terminal / dropped SSH) → land back in
//   'takeover'     — an explicitly named (-S) session is live elsewhere; the user
//                    targeted it by name, so detach the other client and take over
//   'mirror'       — share mode (-M): the target is live elsewhere, attach to it
//                    ALONGSIDE the other client — both mirror the same session,
//                    neither is kicked
//   'new-completed' — the target pane is dead/completed, so create a fresh
//                    sibling instead of attaching to an input-dead pane
// select/upsert + options.share chooses mirror-over-takeover when the target is
// live. Only create is forbidden from entering existing state.
function planPersistentSession(sessions, baseSession, options = {}) {
  const intent = String(options.intent || '').trim();
  if (!['create', 'select', 'upsert'].includes(intent)) {
    const error = new Error('invalid_persistent_session_intent');
    error.code = 'invalid_persistent_session_intent';
    throw error;
  }
  const share = !!options.share;
  const compatibilityOptions = {
    requireUtf8Runtime: !!options.requireUtf8Runtime,
    requireClaudeRenderRuntime: !!options.requireClaudeRenderRuntime,
    requirePsmuxCodexLaunchRuntime: !!options.requirePsmuxCodexLaunchRuntime,
    requireProviderSupervisorRuntime: !!options.requireProviderSupervisorRuntime
  };
  const list = Array.isArray(sessions) ? sessions : [];
  if (intent === 'create') return { session: baseSession, action: 'new' };

  const byName = new Map(list.map((s) => [s.name, s]));
  const base = byName.get(baseSession);
  const incompatibility = getSessionIncompatibility(base, compatibilityOptions);
  const incompatibleAction = () => (
    /^(?:pane-dead|screen-completed)$/.test(incompatibility)
      ? 'new-completed'
      : 'new-compatible'
  );
  const nextReplacementPlan = (fallbackAction) => {
    const prefix = `${baseSession}-`;
    let maxN = 1;
    for (const s of list) {
      if (!s.name.startsWith(prefix)) continue;
      const n = Number(s.name.slice(prefix.length));
      if (!Number.isInteger(n) || n < 2) continue;
      if (n > maxN) maxN = n;
    }
    return { session: `${baseSession}-${maxN + 1}`, action: fallbackAction };
  };

  if (!base) {
    return intent === 'select'
      ? { session: baseSession, action: 'missing' }
      : { session: baseSession, action: 'new' };
  }
  if (incompatibility) {
    return intent === 'select'
      ? { session: baseSession, action: 'unavailable', reason: incompatibility }
      : nextReplacementPlan(incompatibleAction());
  }
  if (!base.attached) return { session: baseSession, action: 'reattach' };
  return { session: baseSession, action: share ? 'mirror' : 'takeover' };
}

// Turn the raw session list into a display model grouped into "this project" vs
// "other projects", each row carrying a ready-to-run command. `cwd` is where the
// user ran `sessions` from, so we can group sessions by project. Pure +
// testable; the router owns interactive exact-target selection.
function describeSessionList(sessions, options = {}) {
  const cliName = String(options.cliName || '').trim();
  const cliSelector = String(options.cliSelector || '').trim();
  const cwd = String(options.cwd || '').trim();
  const shareLive = options.shareLive !== false;
  const pickerCommand = `aih ${cliName} sessions ${cliSelector}`;
  const base = cwd ? deriveSessionName({ cwd }) : '';
  const normPath = (p) => String(p || '').replace(/\/+$/, '');
  const cwdNorm = normPath(cwd);
  // A session belongs to "this project" if it shares the project's generated
  // prefix (name match) OR it was started in this exact directory (path match,
  // covers `-S`-named sessions launched here).
  const belongsToCwd = (s) => Boolean(base) && (
    s.name === base
    || s.name.startsWith(`${base}-`)
    || (cwdNorm && normPath(s.path) === cwdNorm)
  );

  const row = (s) => {
    const completed = Boolean(
      (s.paneDeadChecked && s.paneDead)
      || (s.screenCompletedChecked && s.screenCompleted)
    );
    const live = s.attached && !completed;
    const here = belongsToCwd(s);
    const legacyUtf8Runtime = Boolean(s.utf8RuntimeChecked && !isUtf8RuntimeReadySession(s));
    const legacyClaudeRenderRuntime = cliName === 'claude'
      && Boolean(s.claudeRenderRuntimeChecked && !isClaudeRenderRuntimeReadySession(s));
    const legacyPsmuxCodexLaunchRuntime = cliName === 'codex'
      && Boolean(s.psmuxCodexLaunchRuntimeChecked && !isPsmuxCodexLaunchRuntimeReadySession(s));
    let command;
    if (legacyUtf8Runtime || legacyClaudeRenderRuntime || legacyPsmuxCodexLaunchRuntime || completed) {
      // Do not recommend mirror/resume commands for panes created before the
      // current runtime markers, or for completed/dead panes. A normal launch
      // lets the planner create a clean sibling instead of re-entering a pane
      // that cannot accept input.
      if (here) command = `aih ${cliName} ${cliSelector}`;
      else if (s.path) command = `cd ${shellQuote(s.path)} && aih ${cliName} ${cliSelector}`;
      else command = `（在该项目目录里运行 aih ${cliName} ${cliSelector}）`;
    } else if (s.name.startsWith('s-')) {
      // Explicitly named session: addressable from anywhere by its label. Use
      // mirror mode for live sessions so list guidance never suggests stealing.
      command = `aih ${cliName} ${cliSelector} ${shareLive ? '-M' : '-R'} -S ${s.name.slice(2)}`;
    } else {
      // Auto-generated names are exact identities. A bare provider launch is
      // always fresh, so existing sessions must be selected through the picker.
      command = pickerCommand;
    }
    const description = deriveSessionDescription(s);
    return {
      name: s.name,
      live,
      completed,
      here,
      path: s.path,
      command,
      description,
      agentSessionId: compactSessionText(s.agentSessionId),
      targetSession: s.name
    };
  };

  const rows = sessions.map(row);
  return {
    here: rows.filter((r) => r.here),
    others: rows.filter((r) => !r.here),
    cwd,
    hasCwd: Boolean(base)
  };
}

// Build the argv that lists an account's live persistent sessions, one per line
// as `<name>\t<attached>\t<created>\t<path>` — used by the `aih ... sessions`
// surface so a returning user can see and re-attach what is running.
function buildListSessionsCommand(options = {}) {
  const command = options.tmuxCommand || options.tmuxPath || 'tmux';
  const socket = deriveSocket(options.cliName, options.runtimeScope);
  const format = [
    '#{session_name}',
    '#{session_attached}',
    '#{session_created}',
    '#{session_path}',
    '#{pane_title}',
    '#{window_name}',
    '#{pane_current_command}',
    '#{pane_pid}',
    `#{E:${UTF8_RUNTIME_MARKER_KEY}}`,
    `#{E:${CLAUDE_RENDER_RUNTIME_MARKER_KEY}}`,
    '#{pane_dead}',
    `#{E:${PSMUX_CODEX_LAUNCH_RUNTIME_MARKER_KEY}}`,
    '#{pane_current_path}',
    `#{E:${PROVIDER_SUPERVISOR_RUNTIME_MARKER_KEY}}`
  ].join(SESSION_LIST_SEPARATOR);
  return {
    command,
    args: [
      ...buildTmuxBaseArgs(socket),
      'list-sessions',
      '-F', format
    ],
    socket
  };
}

function buildKillSessionCommand(options = {}) {
  const command = options.tmuxCommand || options.tmuxPath || 'tmux';
  const socket = deriveSocket(options.cliName, options.runtimeScope);
  const session = String(options.sessionName || options.targetSession || '').trim();
  if (!isSafeSessionName(session)) return null;
  return {
    command,
    args: [
      ...buildTmuxBaseArgs(socket),
      'kill-session',
      '-t', session
    ],
    socket,
    session
  };
}

function buildDetachClientCommand(options = {}) {
  const command = options.tmuxCommand || options.tmuxPath || 'tmux';
  const socket = deriveSocket(options.cliName, options.runtimeScope);
  const session = String(options.sessionName || options.targetSession || '').trim();
  if (!isSafeSessionName(session)) return null;
  return {
    command,
    args: [
      ...buildTmuxBaseArgs(socket),
      'detach-client',
      '-s', session
    ],
    socket,
    session
  };
}

function buildCapturePaneCommand(options = {}) {
  const command = options.tmuxCommand || options.tmuxPath || 'tmux';
  const socket = deriveSocket(options.cliName, options.runtimeScope);
  const session = String(options.sessionName || options.targetSession || '').trim();
  if (!isSafeSessionName(session)) return null;
  const start = Number.isFinite(Number(options.start)) ? Math.floor(Number(options.start)) : -80;
  return {
    command,
    args: [
      ...buildTmuxBaseArgs(socket),
      'capture-pane',
      '-p',
      '-t', session,
      '-S', String(start)
    ],
    socket,
    session
  };
}

function buildSourceConfigCommand(options = {}) {
  const command = options.tmuxCommand || options.tmuxPath || 'tmux';
  const socket = deriveSocket(options.cliName, options.runtimeScope);
  const confPath = String(options.confPath || '').trim();
  if (!confPath) return null;
  return {
    command,
    args: [...buildTmuxBaseArgs(socket), 'source-file', confPath],
    socket
  };
}

module.exports = {
  MARKER_ENV,
  DISABLE_ENV,
  SESSION_ENV,
  RESUME_ENV,
  MIRROR_ENV,
  TARGET_ENV,
  DETACHED_ENV,
  PSMUX_INSTALL_URL,
  PSMUX_WINGET_PACKAGE_ID,
  SESSION_LIST_SEPARATOR,
  TRANSPARENT_CONF,
  PSMUX_TRANSPARENT_CONF,
  WINDOWS_TMUX_CANDIDATES,
  GATEWAY_RUNTIME_SCOPE,
  normalizeRuntimeScope,
  sanitizeKeyPart,
  shortHash,
  deriveSocket,
  deriveSessionName,
  deriveFreshSessionName,
  isSafeSessionName,
  deriveSessionDescription,
  collectWindowsTmuxCandidates,
  detectTmux,
  buildWindowsPsmuxInstallCommand,
  installWindowsPsmux,
  shouldPersist,
  ensureTmuxConf,
  getTmuxConfContent,
  isNativeWindowsPsmuxCommand,
  buildTmuxLaunch,
  buildSetEnvironmentCommands,
  buildListSessionsCommand,
  buildDetachClientCommand,
  buildCapturePaneCommand,
  buildKillSessionCommand,
  buildSourceConfigCommand,
  parseSessionList,
  isUtf8RuntimeReadySession,
  isCompletedSessionScreen,
  getSessionIncompatibility,
  isSessionCompatible,
  buildSessionCompatibilityOptions,
  planPersistentSession,
  describeSessionList,
  UTF8_RUNTIME_MARKER_KEY,
  UTF8_RUNTIME_MARKER_VALUE,
  CLAUDE_RENDER_RUNTIME_MARKER_KEY,
  CLAUDE_RENDER_RUNTIME_MARKER_VALUE,
  PSMUX_CODEX_LAUNCH_RUNTIME_MARKER_KEY,
  PSMUX_CODEX_LAUNCH_RUNTIME_MARKER_VALUE,
  PROVIDER_SUPERVISOR_RUNTIME_MARKER_KEY,
  PROVIDER_SUPERVISOR_RUNTIME_MARKER_VALUE,
  isClaudeRenderRuntimeReadySession,
  isPsmuxCodexLaunchRuntimeReadySession,
  isProviderSupervisorRuntimeReadySession,
  _resetDetectCacheForTests() {
    detectCache = null;
  }
};
